@HotelListing.Api_HostAddress = http://localhost:5207

GET {{HotelListing.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
### New Request
# Collection: hotels
GET http://localhost:5207/api/hotels/
: 
: 
Content-Type: application/json

{
    "id": 3,
    "name": "Hotel D",
    "address": "Address CD",
    "rating": 4.0
  }
### New Request
# Collection: countries
POST http://localhost:5207/api/country
Content-Type: application/json
: 
: 
: 
: 

{
   "name": "Test 
}nr

### Get.coun
# Collection: countries
GET http://localhost:5207/api/country
Content-Type: application/json
: 
: 
: 
: 
: 
: 
